[project]
name = "quotation-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.20.0",
    "dotenv>=0.9.9",
    "pydantic>=2.13.5",
    "pydantic-ai-slim[anthropic,google,groq,openai]>=2.42.0",
    "sqlalchemy>=2.0.52",
]
