"""add company research table

Revision ID: 343842948971
Revises: 9d10280cdeab
Create Date: 2026-09-26 18:47:59.838309
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '343842948971'
down_revision: Union[str, None] = '9d10280cdeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('researched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_research')
    # ### end Alembic commands ###
