"""add human request table and workflow states

Revision ID: 983c9bf690a4
Revises: 343842948971
Create Date: 2026-09-26 21:10:10.115328
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '983c9bf690a4'
down_revision: Union[str, None] = '343842948971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queued_job_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('CLARIFICATION', 'APPROVAL', 'PRODUCT_SELECTION', 'PRICE_CONFIRMATION', name='humanrequesttype'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANSWERED', 'REJECTED', 'EXPIRED', name='humanrequeststatus'), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['queued_job_id'], ['queued_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_requests_queued_job_id'), 'human_requests', ['queued_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_requests_queued_job_id'), table_name='human_requests')
    op.drop_table('human_requests')
    # ### end Alembic commands ###
